version: '3.8'

services:
  usuario-service:
    build: ./usuario
    container_name: usuario-service
    ports:
      - "8081:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql:jdbc:postgresql://db_usuário:5432/usuario
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=admin
    networks:
      - reserva-network

  sala-service:
    build: ./sala
    container_name: sala-service
    ports:
      - "8082:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql:jdbc:postgresql://localhost:5434/sala
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=admin
    networks:
      - reserva-network

  reserva-service:
    build: ./reserva
    container_name: reserva-service
    ports:
      - "8083:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql:jdbc:postgresql://localhost:5433/reserva
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=admin
    networks:
      - reserva-network

networks:
  reserva-network:
    driver: bridge
