CREATE TABLE Usuario (
   id SERIAL PRIMARY KEY,
   nome VARCHAR(255) NOT NULL,
   cpf VARCHAR(11) UNIQUE NOT NULL,
   email VARCHAR(255) UNIQUE NOT NULL,
   data_nascimento DATE NOT NULL,
   data_cadastro TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
   rua VARCHAR(255) NOT NULL,
   cidade VARCHAR(255) NOT NULL,
   estado VARCHAR(50) NOT NULL,
   cep VARCHAR(20) NOT NULL,
   senha VARCHAR(255) NOT NULL,
   telefone VARCHAR(20) NOT NULL
);